// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { itemsCreateItem, itemsDeleteItem, itemsReadItem, itemsReadItems, itemsUpdateItem, loginLoginAccessToken, loginRecoverPassword, loginRecoverPasswordHtmlContent, loginResetPassword, loginTestToken, type Options, privateCreateUser, usersCreateUser, usersDeleteUser, usersDeleteUserMe, usersReadUserById, usersReadUserMe, usersReadUsers, usersRegisterUser, usersUpdatePasswordMe, usersUpdateUser, usersUpdateUserMe, utilsHealthCheck, utilsTestEmail } from '../sdk.gen';
import type { ItemsCreateItemData, ItemsCreateItemError, ItemsCreateItemResponse, ItemsDeleteItemData, ItemsDeleteItemError, ItemsDeleteItemResponse, ItemsReadItemData, ItemsReadItemError, ItemsReadItemResponse, ItemsReadItemsData, ItemsReadItemsError, ItemsReadItemsResponse, ItemsUpdateItemData, ItemsUpdateItemError, ItemsUpdateItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenError, LoginLoginAccessTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordError, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentError, LoginRecoverPasswordHtmlContentResponse, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordError, LoginResetPasswordResponse, LoginTestTokenData, LoginTestTokenResponse, PrivateCreateUserData, PrivateCreateUserError, PrivateCreateUserResponse, UsersCreateUserData, UsersCreateUserError, UsersCreateUserResponse, UsersDeleteUserData, UsersDeleteUserError, UsersDeleteUserMeData, UsersDeleteUserMeResponse, UsersDeleteUserResponse, UsersReadUserByIdData, UsersReadUserByIdError, UsersReadUserByIdResponse, UsersReadUserMeData, UsersReadUserMeResponse, UsersReadUsersData, UsersReadUsersError, UsersReadUsersResponse, UsersRegisterUserData, UsersRegisterUserError, UsersRegisterUserResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeError, UsersUpdatePasswordMeResponse, UsersUpdateUserData, UsersUpdateUserError, UsersUpdateUserMeData, UsersUpdateUserMeError, UsersUpdateUserMeResponse, UsersUpdateUserResponse, UtilsHealthCheckData, UtilsHealthCheckResponse, UtilsTestEmailData, UtilsTestEmailError, UtilsTestEmailResponse } from '../types.gen';

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginLoginAccessTokenMutation = (options?: Partial<Options<LoginLoginAccessTokenData>>): UseMutationOptions<LoginLoginAccessTokenResponse, LoginLoginAccessTokenError, Options<LoginLoginAccessTokenData>> => {
    const mutationOptions: UseMutationOptions<LoginLoginAccessTokenResponse, LoginLoginAccessTokenError, Options<LoginLoginAccessTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginLoginAccessToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Test Token
 *
 * Test access token
 */
export const loginTestTokenMutation = (options?: Partial<Options<LoginTestTokenData>>): UseMutationOptions<LoginTestTokenResponse, DefaultError, Options<LoginTestTokenData>> => {
    const mutationOptions: UseMutationOptions<LoginTestTokenResponse, DefaultError, Options<LoginTestTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginTestToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Recover Password
 *
 * Password Recovery
 */
export const loginRecoverPasswordMutation = (options?: Partial<Options<LoginRecoverPasswordData>>): UseMutationOptions<LoginRecoverPasswordResponse, LoginRecoverPasswordError, Options<LoginRecoverPasswordData>> => {
    const mutationOptions: UseMutationOptions<LoginRecoverPasswordResponse, LoginRecoverPasswordError, Options<LoginRecoverPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginRecoverPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset Password
 *
 * Reset password
 */
export const loginResetPasswordMutation = (options?: Partial<Options<LoginResetPasswordData>>): UseMutationOptions<LoginResetPasswordResponse, LoginResetPasswordError, Options<LoginResetPasswordData>> => {
    const mutationOptions: UseMutationOptions<LoginResetPasswordResponse, LoginResetPasswordError, Options<LoginResetPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginResetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Recover Password Html Content
 *
 * HTML Content for Password Recovery
 */
export const loginRecoverPasswordHtmlContentMutation = (options?: Partial<Options<LoginRecoverPasswordHtmlContentData>>): UseMutationOptions<LoginRecoverPasswordHtmlContentResponse, LoginRecoverPasswordHtmlContentError, Options<LoginRecoverPasswordHtmlContentData>> => {
    const mutationOptions: UseMutationOptions<LoginRecoverPasswordHtmlContentResponse, LoginRecoverPasswordHtmlContentError, Options<LoginRecoverPasswordHtmlContentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginRecoverPasswordHtmlContent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersReadUsersQueryKey = (options?: Options<UsersReadUsersData>) => createQueryKey('usersReadUsers', options);

/**
 * Read Users
 *
 * Retrieve users.
 */
export const usersReadUsersOptions = (options?: Options<UsersReadUsersData>) => queryOptions<UsersReadUsersResponse, UsersReadUsersError, UsersReadUsersResponse, ReturnType<typeof usersReadUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersReadUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersReadUsersQueryKey(options)
});

/**
 * Create User
 *
 * Create new user.
 */
export const usersCreateUserMutation = (options?: Partial<Options<UsersCreateUserData>>): UseMutationOptions<UsersCreateUserResponse, UsersCreateUserError, Options<UsersCreateUserData>> => {
    const mutationOptions: UseMutationOptions<UsersCreateUserResponse, UsersCreateUserError, Options<UsersCreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersCreateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMeMutation = (options?: Partial<Options<UsersDeleteUserMeData>>): UseMutationOptions<UsersDeleteUserMeResponse, DefaultError, Options<UsersDeleteUserMeData>> => {
    const mutationOptions: UseMutationOptions<UsersDeleteUserMeResponse, DefaultError, Options<UsersDeleteUserMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersDeleteUserMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersReadUserMeQueryKey = (options?: Options<UsersReadUserMeData>) => createQueryKey('usersReadUserMe', options);

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMeOptions = (options?: Options<UsersReadUserMeData>) => queryOptions<UsersReadUserMeResponse, DefaultError, UsersReadUserMeResponse, ReturnType<typeof usersReadUserMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersReadUserMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersReadUserMeQueryKey(options)
});

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMeMutation = (options?: Partial<Options<UsersUpdateUserMeData>>): UseMutationOptions<UsersUpdateUserMeResponse, UsersUpdateUserMeError, Options<UsersUpdateUserMeData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdateUserMeResponse, UsersUpdateUserMeError, Options<UsersUpdateUserMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersUpdateUserMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersUpdatePasswordMeMutation = (options?: Partial<Options<UsersUpdatePasswordMeData>>): UseMutationOptions<UsersUpdatePasswordMeResponse, UsersUpdatePasswordMeError, Options<UsersUpdatePasswordMeData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdatePasswordMeResponse, UsersUpdatePasswordMeError, Options<UsersUpdatePasswordMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersUpdatePasswordMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register User
 *
 * Create new user without the need to be logged in.
 */
export const usersRegisterUserMutation = (options?: Partial<Options<UsersRegisterUserData>>): UseMutationOptions<UsersRegisterUserResponse, UsersRegisterUserError, Options<UsersRegisterUserData>> => {
    const mutationOptions: UseMutationOptions<UsersRegisterUserResponse, UsersRegisterUserError, Options<UsersRegisterUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersRegisterUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 *
 * Delete a user.
 */
export const usersDeleteUserMutation = (options?: Partial<Options<UsersDeleteUserData>>): UseMutationOptions<UsersDeleteUserResponse, UsersDeleteUserError, Options<UsersDeleteUserData>> => {
    const mutationOptions: UseMutationOptions<UsersDeleteUserResponse, UsersDeleteUserError, Options<UsersDeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersDeleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersReadUserByIdQueryKey = (options: Options<UsersReadUserByIdData>) => createQueryKey('usersReadUserById', options);

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const usersReadUserByIdOptions = (options: Options<UsersReadUserByIdData>) => queryOptions<UsersReadUserByIdResponse, UsersReadUserByIdError, UsersReadUserByIdResponse, ReturnType<typeof usersReadUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersReadUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersReadUserByIdQueryKey(options)
});

/**
 * Update User
 *
 * Update a user.
 */
export const usersUpdateUserMutation = (options?: Partial<Options<UsersUpdateUserData>>): UseMutationOptions<UsersUpdateUserResponse, UsersUpdateUserError, Options<UsersUpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdateUserResponse, UsersUpdateUserError, Options<UsersUpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersUpdateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Test Email
 *
 * Test emails.
 */
export const utilsTestEmailMutation = (options?: Partial<Options<UtilsTestEmailData>>): UseMutationOptions<UtilsTestEmailResponse, UtilsTestEmailError, Options<UtilsTestEmailData>> => {
    const mutationOptions: UseMutationOptions<UtilsTestEmailResponse, UtilsTestEmailError, Options<UtilsTestEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await utilsTestEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const utilsHealthCheckQueryKey = (options?: Options<UtilsHealthCheckData>) => createQueryKey('utilsHealthCheck', options);

/**
 * Health Check
 */
export const utilsHealthCheckOptions = (options?: Options<UtilsHealthCheckData>) => queryOptions<UtilsHealthCheckResponse, DefaultError, UtilsHealthCheckResponse, ReturnType<typeof utilsHealthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await utilsHealthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: utilsHealthCheckQueryKey(options)
});

export const itemsReadItemsQueryKey = (options?: Options<ItemsReadItemsData>) => createQueryKey('itemsReadItems', options);

/**
 * Read Items
 *
 * Retrieve items.
 */
export const itemsReadItemsOptions = (options?: Options<ItemsReadItemsData>) => queryOptions<ItemsReadItemsResponse, ItemsReadItemsError, ItemsReadItemsResponse, ReturnType<typeof itemsReadItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await itemsReadItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: itemsReadItemsQueryKey(options)
});

/**
 * Create Item
 *
 * Create new item.
 */
export const itemsCreateItemMutation = (options?: Partial<Options<ItemsCreateItemData>>): UseMutationOptions<ItemsCreateItemResponse, ItemsCreateItemError, Options<ItemsCreateItemData>> => {
    const mutationOptions: UseMutationOptions<ItemsCreateItemResponse, ItemsCreateItemError, Options<ItemsCreateItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await itemsCreateItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Item
 *
 * Delete an item.
 */
export const itemsDeleteItemMutation = (options?: Partial<Options<ItemsDeleteItemData>>): UseMutationOptions<ItemsDeleteItemResponse, ItemsDeleteItemError, Options<ItemsDeleteItemData>> => {
    const mutationOptions: UseMutationOptions<ItemsDeleteItemResponse, ItemsDeleteItemError, Options<ItemsDeleteItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await itemsDeleteItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const itemsReadItemQueryKey = (options: Options<ItemsReadItemData>) => createQueryKey('itemsReadItem', options);

/**
 * Read Item
 *
 * Get item by ID.
 */
export const itemsReadItemOptions = (options: Options<ItemsReadItemData>) => queryOptions<ItemsReadItemResponse, ItemsReadItemError, ItemsReadItemResponse, ReturnType<typeof itemsReadItemQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await itemsReadItem({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: itemsReadItemQueryKey(options)
});

/**
 * Update Item
 *
 * Update an item.
 */
export const itemsUpdateItemMutation = (options?: Partial<Options<ItemsUpdateItemData>>): UseMutationOptions<ItemsUpdateItemResponse, ItemsUpdateItemError, Options<ItemsUpdateItemData>> => {
    const mutationOptions: UseMutationOptions<ItemsUpdateItemResponse, ItemsUpdateItemError, Options<ItemsUpdateItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await itemsUpdateItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create User
 *
 * Create a new user.
 */
export const privateCreateUserMutation = (options?: Partial<Options<PrivateCreateUserData>>): UseMutationOptions<PrivateCreateUserResponse, PrivateCreateUserError, Options<PrivateCreateUserData>> => {
    const mutationOptions: UseMutationOptions<PrivateCreateUserResponse, PrivateCreateUserError, Options<PrivateCreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await privateCreateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
